# ubuntu:focal refers to the Docker image for Ubuntu 20.04 LTS,
FROM ubuntu:focal 

RUN apt-get update
RUN apt-get install -y curl

# Install NodeJS and Git
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

RUN apt-get install git -y

WORKDIR /home/app
COPY main.sh main.sh
COPY script.js script.js
COPY package*.json .

RUN npm install

# Make them executable
RUN chmod +x main.sh
RUN chmod +x script.js

# Run the Script file
ENTRYPOINT [ "/home/app/main.sh" ]

